import Header from '../components/Header';

export default function Terms() {
  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <Header showBackButton={true} />

      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-600">Last updated: January 11, 2025</p>
        </div>

        <div className="prose prose-lg max-w-none">
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Agreement to Terms</h2>
              <p className="text-gray-600 leading-relaxed">
                By accessing and using NexVision (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). 
                If you disagree with any part of these terms, then you may not access the Service. These Terms apply to 
                all visitors, users, and others who access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Description of Service</h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                NexVision is an AI-powered service that transforms exterior home photos based on user descriptions. 
                Our Service includes:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>AI-generated exterior home transformations</li>
                <li>Image upload and processing capabilities</li>
                <li>Credit-based usage system</li>
                <li>Free trial and paid subscription options</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">User Accounts and Credits</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Free Trial</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600 mb-6">
                <li>New users receive 3 free transformation credits</li>
                <li>No account creation required for free trial</li>
                <li>Credits are tracked by device/browser session</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Pro Subscription</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>$9.99 for 50 transformation credits</li>
                <li>Credits do not expire</li>
                <li>Priority processing for Pro users</li>
                <li>Email support included</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Acceptable Use</h2>
              <p className="text-gray-600 leading-relaxed mb-4">You agree to use NexVision only for lawful purposes and in accordance with these Terms. You agree NOT to:</p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>Upload images you do not own or have permission to use</li>
                <li>Upload inappropriate, offensive, or illegal content</li>
                <li>Attempt to reverse engineer or copy our AI technology</li>
                <li>Use the Service to create content that violates others&apos; rights</li>
                <li>Attempt to circumvent usage limits or payment systems</li>
                <li>Use automated systems to access the Service without permission</li>
                <li>Upload images containing people without their consent</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Content and Intellectual Property</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Your Content</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600 mb-6">
                <li>You retain ownership of images you upload</li>
                <li>You grant us temporary rights to process your images for transformation</li>
                <li>You own the rights to transformed images generated by our Service</li>
                <li>You may use transformed images for personal or commercial purposes</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Our Content</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>NexVision&apos;s AI technology, software, and Service are our intellectual property</li>
                <li>You may not copy, modify, or distribute our technology</li>
                <li>Our trademarks and branding remain our property</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Payment and Refunds</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Payment Processing</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600 mb-6">
                <li>Payments are processed securely through third-party providers</li>
                <li>All prices are in USD unless otherwise specified</li>
                <li>You authorize us to charge your payment method for purchases</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Refund Policy</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>Refunds may be provided at our discretion for technical issues</li>
                <li>No refunds for used credits or completed transformations</li>
                <li>Contact support within 7 days for refund requests</li>
                <li>Refunds will be processed to the original payment method</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Availability and Limitations</h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                We strive to provide reliable service, but cannot guarantee:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>100% uptime or availability</li>
                <li>Perfect transformation results for all images</li>
                <li>Specific processing times (though we target under 30 seconds)</li>
                <li>Compatibility with all devices or browsers</li>
              </ul>
              <p className="text-gray-600 leading-relaxed mt-4">
                We reserve the right to modify, suspend, or discontinue the Service at any time with reasonable notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimers and Limitations</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">AI-Generated Content</h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-600 mb-6">
                <li>Transformations are conceptual visualizations, not architectural plans</li>
                <li>Results may not be structurally or practically feasible</li>
                <li>Always consult professionals for actual renovation planning</li>
                <li>We do not guarantee accuracy of architectural details</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Limitation of Liability</h3>
              <p className="text-gray-600 leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEXVISION SHALL NOT BE LIABLE FOR ANY INDIRECT, 
                INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, 
                WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER 
                INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Privacy</h2>
              <p className="text-gray-600 leading-relaxed">
                Your privacy is important to us. Please review our Privacy Policy, which also governs your use 
                of the Service, to understand our practices regarding the collection and use of your information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Termination</h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, 
                for any reason whatsoever, including without limitation if you breach the Terms.
              </p>
              <p className="text-gray-600 leading-relaxed">
                Upon termination, your right to use the Service will cease immediately. Unused credits may be 
                forfeited upon termination for Terms violations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to Terms</h2>
              <p className="text-gray-600 leading-relaxed">
                We reserve the right to modify or replace these Terms at any time. If a revision is material, 
                we will try to provide at least 30 days notice prior to any new terms taking effect. 
                What constitutes a material change will be determined at our sole discretion.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Governing Law</h2>
              <p className="text-gray-600 leading-relaxed">
                These Terms shall be interpreted and governed by the laws of the State of Delaware, United States, 
                without regard to its conflict of law provisions. Any disputes arising from these Terms or the 
                Service will be resolved in the courts of Delaware.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                If you have any questions about these Terms of Service, please contact us:
              </p>
              <div className="bg-gray-50 p-6 rounded-lg">
                <p className="text-gray-600 mb-2"><strong>Email:</strong> <a href="mailto:legal@nexvision.app" className="text-blue-600 hover:text-blue-700">legal@nexvision.app</a></p>
                <p className="text-gray-600 mb-2"><strong>Support:</strong> <a href="mailto:support@nexvision.app" className="text-blue-600 hover:text-blue-700">support@nexvision.app</a></p>
                <p className="text-gray-600"><strong>Address:</strong> NexVision, LLC, Delaware, United States</p>
              </div>
            </section>

            <section className="border-t border-gray-200 pt-8">
              <p className="text-sm text-gray-500">
                By using NexVision, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
